"""Correctly adding Foreign Key to FavBook

Revision ID: 361b09948f48
Revises: 45a7efd6e59a
Create Date: 2020-12-03 23:25:06.272818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361b09948f48'
down_revision = '45a7efd6e59a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fav_book', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'fav_book', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fav_book', type_='foreignkey')
    op.alter_column('fav_book', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
