"""Adding Foreign Key to FavBook

Revision ID: 45a7efd6e59a
Revises: 4dddfccb17a9
Create Date: 2020-12-03 23:20:36.578286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a7efd6e59a'
down_revision = '4dddfccb17a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fav_book', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fav_book', 'user_id')
    # ### end Alembic commands ###
