"""Trying to add simplified FavBooks model

Revision ID: 4dddfccb17a9
Revises: b27a732c0b81
Create Date: 2020-12-03 22:53:10.210660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4dddfccb17a9'
down_revision = 'b27a732c0b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=254), nullable=True),
    sa.Column('authors', sa.String(length=750), nullable=True),
    sa.Column('average_rating', sa.Numeric(), nullable=True),
    sa.Column('isbn', sa.String(length=10), nullable=True),
    sa.Column('isbn13', sa.String(length=13), nullable=True),
    sa.Column('language_code', sa.String(length=5), nullable=True),
    sa.Column('num_pages', sa.Integer(), nullable=True),
    sa.Column('ratings_count', sa.Integer(), nullable=True),
    sa.Column('text_reviews_count', sa.Integer(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('publisher', sa.String(length=67), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('book_details')
    op.add_column('fav_book', sa.Column('isbn13', sa.String(length=13), nullable=True))
    op.drop_constraint('fav_book_user_id_fkey', 'fav_book', type_='foreignkey')
    op.drop_column('fav_book', 'author')
    op.drop_column('fav_book', 'user_id')
    op.drop_column('fav_book', 'title')
    op.drop_column('fav_book', 'date_created')
    op.drop_column('fav_book', 'cover')
    op.drop_column('fav_book', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fav_book', sa.Column('description', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('fav_book', sa.Column('cover', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('fav_book', sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('fav_book', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('fav_book', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('fav_book', sa.Column('author', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_foreign_key('fav_book_user_id_fkey', 'fav_book', 'user', ['user_id'], ['id'])
    op.drop_column('fav_book', 'isbn13')
    op.create_table('book_details',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('authors', sa.VARCHAR(length=750), autoincrement=False, nullable=False),
    sa.Column('average_rating', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=False),
    sa.Column('isbn', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('isbn13', sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    sa.Column('language_code', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('num_pages', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ratings_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text_reviews_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('publication_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('publisher', sa.VARCHAR(length=67), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='book_details_pkey')
    )
    op.drop_table('book_detail')
    # ### end Alembic commands ###
